import '../during_trip/stop.dart';

Map<String, List<Stop>> allTrips = {
  'trip1': [
    Stop(
      name: "El-Moez",
      avgTime: 60,
      distance: 30.0,
      isActive: true,
      description: "A hidden waterfall in a magical forest.",
      isFinished: false,
      isRemoved: false,
      image: 'elmoezz.jpg',
      directions: "https://maps.app.goo.gl/7JzQAbw8x8xQRDUM7",
    ),
    Stop(
      name: "Al-Hussein Mosque",
      avgTime: 20,
      distance: 55.5,
      isActive: false,
      description:
          "Sunbathe on the golden sands and swim in crystal-clear waters.",
      isFinished: false,
      isRemoved: false,
      image: './assets/images/dog.png',
      directions: "https://maps.app.goo.gl/Vg3dncPdees9x2ee9",
    ),
    Stop(
      name: "Bab Zuweila",
      avgTime: 30,
      distance: 15.7,
      isActive: false,
      description:
          "A mystical forest with talking animals and glowing mushrooms.",
      isFinished: false,
      isRemoved: false,
      image: './assets/images/dog.png',
      directions: "https://maps.app.goo.gl/gEgkbVJTo3YbYsHv7",
    ),
    Stop(
      name: "Khan El-Khalily",
      avgTime: 60,
      distance: 18.9,
      isActive: false,
      description: "A serene lake with water as blue as sapphires.",
      isFinished: false,
      isRemoved: false,
      image: './assets/images/dog.png',
      directions: "https://maps.app.goo.gl/Mox3n6Vac2t1VS4u8",
    ),
    Stop(
      name: "Om Kolthoom Cafe",
      avgTime: 60,
      distance: 42.1,
      isActive: false,
      description: "A lighthouse that never goes out, guiding ships safely.",
      isFinished: false,
      isRemoved: false,
      image: './assets/images/dog.png',
      directions: "https://maps.app.goo.gl/uBRFfKNF1S4HevY27",
    ),
    Stop(
      name: "Jordi Bazar Shop",
      avgTime: 30,
      distance: 63.5,
      isActive: false,
      description: "Rumored home of a friendly dragon.",
      isFinished: false,
      isRemoved: false,
      image: './assets/images/dog.png',
      directions: "https://maps.app.goo.gl/DgUCBsYttRBaCfbDA",
    ),
  ],
  'trip2': [
    Stop(
      name: "The Cave Church",
      avgTime: 120,
      distance: 45.5,
      isActive: true,
      description: "A cave filled with shimmering crystals.",
      isFinished: false,
      isRemoved: false,
      image: 'cavechurch.jpg',
      directions: "https://maps.app.goo.gl/x2gHdo4128bjaCMQ7",
    ),
    Stop(
      name: "Salaheldin Citadel",
      avgTime: 90,
      distance: 35.0,
      isActive: false,
      description: "Fields of fragrant lavender in full bloom.",
      isFinished: false,
      isRemoved: false,
      image: './assets/images/dog.png',
      directions: "https://maps.app.goo.gl/YQ7gaqS3Y29kh6Es9",
    ),
    Stop(
      name: "Mohamed Ali Mosque",
      avgTime: 25,
      distance: 20.8,
      isActive: false,
      description: "Home to mischievous but charming pixies.",
      isFinished: false,
      isRemoved: false,
      image: './assets/images/dog.png',
      directions: "https://maps.app.goo.gl/PAyYWKHZ9FnvUGcR7",
    ),
    Stop(
      name: "National Military Museum",
      avgTime: 30,
      distance: 38.4,
      isActive: false,
      description: "A lake with water as green as emeralds.",
      isFinished: false,
      isRemoved: false,
      image: './assets/images/dog.png',
      directions: "https://maps.app.goo.gl/nf5RuU5dARmi6DJf8",
    ),
    Stop(
      name: "National Police Museum",
      avgTime: 20,
      distance: 32.7,
      isActive: false,
      description: "Ideal spot for whale watching.",
      isFinished: false,
      isRemoved: false,
      image: './assets/images/dog.png',
      directions: "https://maps.app.goo.gl/y3DoDHfjXQKXjgUC9",
    ),
    Stop(
      name: "Al-Azhar Park",
      avgTime: 60,
      distance: 22.3,
      isActive: false,
      description: "A bustling market run by mischievous goblins.",
      isFinished: false,
      isRemoved: false,
      image: './assets/images/dog.png',
      directions: "https://maps.app.goo.gl/cjNkiGUVyY7HZ2tD7",
    ),
    Stop(
      name: "Genena Mall",
      avgTime: 100,
      distance: 47.9,
      isActive: false,
      description: "Best spot to witness the Aurora Borealis.",
      isFinished: false,
      isRemoved: false,
      image: './assets/images/dog.png',
      directions: "https://maps.app.goo.gl/n7EBDTvBBC21K8Kp6",
    ),
  ]
};
