import '../during_trip/stop.dart';

Map<String, List<Stop>> allTrips = {
  'trip1': [
    Stop(
        name: "Mystic Falls",
        avgTime: 45.5,
        distance: 30.0,
        isActive: true,
        description: "A hidden waterfall in a magical forest.",
        isFinished: false,
        image: './assets/images/dog.png'),
    Stop(
        name: "Golden Sands Beach",
        avgTime: 60.0,
        distance: 55.5,
        isActive: false,
        description:
            "Sunbathe on the golden sands and swim in crystal-clear waters.",
        isFinished: false,
        image: './assets/images/dog.png'),
    Stop(
        name: "Enchanted Woods",
        avgTime: 25.3,
        distance: 15.7,
        isActive: false,
        description:
            "A mystical forest with talking animals and glowing mushrooms.",
        isFinished: false,
        image: './assets/images/dog.png'),
    Stop(
        name: "Sapphire Lake",
        avgTime: 35.2,
        distance: 18.9,
        isActive: false,
        description: "A serene lake with water as blue as sapphires.",
        isFinished: false,
        image: './assets/images/dog.png'),
    Stop(
        name: "Eternal Lighthouse",
        avgTime: 60.7,
        distance: 42.1,
        isActive: false,
        description: "A lighthouse that never goes out, guiding ships safely.",
        isFinished: false,
        image: './assets/images/dog.png'),
    Stop(
        name: "Dragon's Lair",
        avgTime: 70.0,
        distance: 63.5,
        isActive: false,
        description: "Rumored home of a friendly dragon.",
        isFinished: false,
        image: './assets/images/dog.png'),
    Stop(
        name: "Moonlit Meadow",
        avgTime: 50.8,
        distance: 37.2,
        isActive: false,
        description: "A meadow that glows under the moonlight.",
        isFinished: false,
        image: './assets/images/dog.png'),
    Stop(
        name: "Hidden Treasure Cave",
        avgTime: 90.2,
        distance: 72.4,
        isActive: false,
        description: "Rumored to hold pirate treasures.",
        isFinished: false,
        image: './assets/images/dog.png'),
    Stop(
        name: "Whispering Waterfall",
        avgTime: 40.6,
        distance: 26.8,
        isActive: false,
        description: "A waterfall with a soothing, whispering sound.",
        isFinished: false,
        image: './assets/images/dog.png'),
    Stop(
        name: "Eclipse Summit",
        avgTime: 55.4,
        distance: 38.7,
        isActive: false,
        description: "A mountaintop with breathtaking eclipse views.",
        isFinished: false,
        image: './assets/images/dog.png'),
  ],
  'trip2': [
    Stop(
        name: "Crystal Caverns",
        avgTime: 70.0,
        distance: 45.5,
        isActive: true,
        description: "A cave filled with shimmering crystals.",
        isFinished: false,
        image: './assets/images/dog.png'),
    Stop(
        name: "Lavender Fields",
        avgTime: 40.5,
        distance: 35.0,
        isActive: false,
        description: "Fields of fragrant lavender in full bloom.",
        isFinished: false,
        image: './assets/images/dog.png'),
    Stop(
        name: "Pixie Hollow",
        avgTime: 30.3,
        distance: 20.8,
        isActive: false,
        description: "Home to mischievous but charming pixies.",
        isFinished: false,
        image: './assets/images/dog.png'),
    Stop(
        name: "Emerald Lake",
        avgTime: 55.1,
        distance: 38.4,
        isActive: false,
        description: "A lake with water as green as emeralds.",
        isFinished: false,
        image: './assets/images/dog.png'),
    Stop(
        name: "Whale Watching Point",
        avgTime: 45.8,
        distance: 32.7,
        isActive: false,
        description: "Ideal spot for whale watching.",
        isFinished: false,
        image: './assets/images/dog.png'),
    Stop(
        name: "Goblin Market",
        avgTime: 35.7,
        distance: 22.3,
        isActive: false,
        description: "A bustling market run by mischievous goblins.",
        isFinished: false,
        image: './assets/images/dog.png'),
    Stop(
        name: "Aurora Overlook",
        avgTime: 60.2,
        distance: 47.9,
        isActive: false,
        description: "Best spot to witness the Aurora Borealis.",
        isFinished: false,
        image: './assets/images/dog.png'),
    Stop(
        name: "Phoenix Nest",
        avgTime: 75.5,
        distance: 65.2,
        isActive: false,
        description: "Rumored resting place of a mythical phoenix.",
        isFinished: false,
        image: './assets/images/dog.png'),
    Stop(
        name: "Eternal Sunset Beach",
        avgTime: 50.1,
        distance: 44.3,
        isActive: false,
        description: "Experience a never-ending sunset.",
        isFinished: false,
        image: './assets/images/dog.png'),
    Stop(
        name: "Starfall Observatory",
        avgTime: 65.8,
        distance: 52.6,
        isActive: false,
        description: "Witness meteor showers at this observatory.",
        isFinished: false,
        image: './assets/images/dog.png'),
  ]
};
