import 'package:indeoendent_tourist_app_main/history_page/ended_trip.dart';

List<EndedTrip> historyTrips = [
  EndedTrip(
    name: "ELMOEZ",
    image: "elmoezz.jpg",
    time: 5,
    money: 5,
    distance: 4,
    numberOfStops: 5,
    rating: 3,
    date: DateTime(2021, 7, 22),
    showDate: false,
  ),
  EndedTrip(
    name: "ELMOEZ",
    image: "elmoezz.jpg",
    time: 5,
    money: 5,
    distance: 4,
    numberOfStops: 5,
    rating: 3,
    date: DateTime(2021, 7, 22),
    showDate: false,
  ),
  EndedTrip(
    name: "ELMOEZ",
    image: "elmoezz.jpg",
    time: 5,
    money: 5,
    distance: 4,
    numberOfStops: 5,
    rating: 3,
    date: DateTime(2021, 7, 22),
    showDate: false,
  ),
  EndedTrip(
    name: "ELMOEZ",
    image: "elmoezz.jpg",
    time: 5,
    money: 5,
    distance: 4,
    numberOfStops: 5,
    rating: 3,
    date: DateTime(2021, 11, 18),
    showDate: false,
  ),
  EndedTrip(
    name: "ELMOEZ",
    image: "elmoezz.jpg",
    time: 5,
    money: 5,
    distance: 4,
    numberOfStops: 5,
    rating: 3,
    date: DateTime(2021, 11, 18),
    showDate: false,
  ),
  EndedTrip(
    name: "ELMOEZ",
    image: "elmoezz.jpg",
    time: 5,
    money: 5,
    distance: 4,
    numberOfStops: 5,
    rating: 3,
    date: DateTime(2021, 11, 19),
    showDate: false,
  ),
  EndedTrip(
    name: "ELMOEZ",
    image: "elmoezz.jpg",
    time: 5,
    money: 5,
    distance: 4,
    numberOfStops: 5,
    rating: 4,
    date: DateTime(2022, 5, 5),
    showDate: false,
  ),
  EndedTrip(
    name: "ELMOEZ",
    image: "elmoezz.jpg",
    time: 5,
    money: 5,
    distance: 4,
    numberOfStops: 5,
    rating: 4,
    date: DateTime(2023, 9, 10),
    showDate: false,
  ),
  EndedTrip(
    name: "ELMOEZ",
    image: "elmoezz.jpg",
    time: 5,
    money: 5,
    distance: 4,
    numberOfStops: 5,
    rating: 4,
    date: DateTime(2023, 9, 10),
    showDate: false,
  ),
  // Add more EndedTrip objects as needed.
];
